var hoteles = [
  {
    "documentName" : "7KALE BED & BREAKFAST",
    "turismDescription" : "Situada en pleno centro de Bilbao resulta perfecta para visitar a pie algunos de los principales ...",
    "turismDescription" : "<p>Situada en pleno centro de Bilbao resulta perfecta para visitar a pie algunos de los principales lugares de inter&eacute s tur&iacute stico, como el Museo Guggenheim, el Teatro Arriaga o la Catedral de Santiago. Adem&aacute s se encuentra a 200 metros de la parada de tranv&iacute a Arriaga, a 300 metros de la parada de metro Casco Viejo y a menos de 10 minutos andando de la estaci&oacute n de tren de Abando. Ofrecen la posibilidad de proporcionar informaci&oacute n tur&iacute stica, guardar equipajes e imprimir las tarjetas de embarque.</p>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "",
    "address" : "Santa María  13",
    "marks" : "Bilbao",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "7kale@7kalebnb.com",
    "web" : "https://www.7kalebnb.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01111",
    "visit" : "",
    "capacity" : "40",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.005",
    "latitudelongitude" : "43.25783022,-2.92541782",
    "latwgs84" : "43.25783022",
    "lonwgs84" : "-2.92541782",
    "placename" : "",
    "address" : "",
    "municipality" : "Bilbao",
    "municipalitycode" : "20",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-7kale-and-breakfast/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000190_a1_rec_turismo/es_190/190-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000190_a1_rec_turismo/es_190/data/190_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000190_a1_rec_turismo/r01Index/0000000190_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000190_a1_rec_turismo/opendata/0000000190_a1_rec_turismo.zip"
  }, {
    "documentName" : "AB DOMINI",
    "turismDescription" : "La pensión Ab Domini se encuentra en pleno corazón de la Parte Vieja de San Sebastián. Las habita...",
    "turismDescription" : "La pensión Ab Domini se encuentra en pleno corazón de la Parte Vieja de San Sebastián. Las habitaciones cuentan con televisión, calefacción, mini bar, Internet (WIFI), caja de seguridad y secador de pelo. Además, la pensión dispone de ascensor, carta de almohadas y cunas, entre otros servicios. Algunas de las habitaciones cuentan con baño propio, y el resto con baño compartido.",
    "templateType" : "Alojamientos",
    "locality" : "Donostia / San Sebastián",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 420 431",
    "address" : "San Juan  8",
    "marks" : "Costa Vasca,San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "1",
    "tourismEmail" : "reservas@abpensiones.com",
    "web" : "http://www.abpensiones.com/",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00649",
    "visit" : "",
    "capacity" : "10",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.003",
    "latitudelongitude" : "43.324385,-1.9836416",
    "latwgs84" : "43.324385",
    "lonwgs84" : "-1.9836416",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamiento/pension-ab-domini/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000043182_a1_rec_turismo/es_43182/43182-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000043182_a1_rec_turismo/es_43182/data/43182_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000043182_a1_rec_turismo/r01Index/0000043182_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000043182_a1_rec_turismo/opendata/0000043182_a1_rec_turismo.zip"
  }, {
    "documentName" : "ABANDO",
    "turismDescription" : "Hotel de cuatro estrellas ubicado en un moderno edificio reformado de decoración vanguardi...",
    "turismDescription" : "<p>Hotel de cuatro estrellas ubicado en un moderno edificio reformado de decoraci&oacute n vanguardista. Est&aacute  situado frente al Palacio de Justicia y pr&oacute ximo al museo Guggenheim, el Casco Viejo, el Teatro Arriaga o el Palacio Euskalduna. Dispone de habitaciones dobles e individuales provistas de caja fuerte, internet, calefacci&oacute n, aire acondicionado, televisi&oacute n por cable, mini-bar y secador de pelo. El hotel ofrece servicio de habitaciones, lavander&iacute a y tintorer&iacute a y entre sus instalaciones cuenta con cafeter&iacute a-bar, restaurante, sala de banquetes, sala de reuniones, sal&oacute n social, biblioteca, sauna, gimnasio y tienda.</p>",
    "templateType" : "Alojamientos",
    "locality" : "Bilbao",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "944 236 200",
    "address" : "Colón de Larreategui  9",
    "marks" : "Bilbao",
    "physical" : "Es practicable para personas con diversidad funcional física",
    "visual" : "Es practicable para personas con diversidad funcional visual",
    "auditive" : "Es practicable para personas con diversidad funcional auditiva",
    "intellectual" : "Está adaptado para personas con diversidad funcional intelectual",
    "organic" : "Está adaptado para personas con diversidad funcional orgánica",
    "qualityAssurance" : "",
    "tourismEmail" : "abando@aranzazu-hoteles.com",
    "web" : "http://www.aranzazu-hoteles.com",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "4",
    "restaurant" : "",
    "room" : "1",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01056",
    "visit" : "",
    "capacity" : "259",
    "store" : "1",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.001",
    "latitudelongitude" : "43.2624787,-2.927723",
    "latwgs84" : "43.2624787",
    "lonwgs84" : "-2.927723",
    "placename" : "",
    "address" : "",
    "municipality" : "Bilbao",
    "municipalitycode" : "20",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamiento/hotel-abando/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000005_a1_rec_turismo/es_5/5-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000005_a1_rec_turismo/es_5/data/5_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000005_a1_rec_turismo/r01Index/0000000005_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000005_a1_rec_turismo/opendata/0000000005_a1_rec_turismo.zip"
  }, {
    "documentName" : "ABBA JAZZ",
    "turismDescription" : "Hotel ubicado en la zona comercial y de negocios de Vitoria-Gasteiz. Está junto a algunos de los ...",
    "turismDescription" : "Hotel ubicado en la zona comercial y de negocios de Vitoria-Gasteiz. Está junto a algunos de los rincones más emblemáticos de la capital alavesa como la Plaza de la Virgen Blanca o el Parque de La Florida y a 300 metros de la estación de tren. Todas las habitaciones, de diseño moderno y funcional cuentan con conexión gratuita de WiFi y escritorio. Algunas de ellas poseen balcón privado.",
    "templateType" : "Alojamientos",
    "locality" : "Vitoria-Gasteiz",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "945.101.346,0",
    "address" : "Florida 7",
    "marks" : "Vitoria-Gasteiz",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "abbajazz@abbahoteles.com",
    "web" : "http://www.abbajazzvitoriahotel.com/",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "3",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HVI00403",
    "visit" : "",
    "capacity" : "37",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "1.005",
    "latitudelongitude" : "42.8435985,-2.6750500000000557",
    "latwgs84" : "42.8435985",
    "lonwgs84" : "-2.6750500000000557",
    "placename" : "",
    "address" : "",
    "municipality" : "Vitoria-Gasteiz",
    "municipalitycode" : "59",
    "postalcode" : "",
    "territory" : "Araba/Álava",
    "territorycode" : "1",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamiento/hotel-abba-jazz/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000060481_a1_rec_turismo/es_60481/60481-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000060481_a1_rec_turismo/es_60481/data/60481_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000060481_a1_rec_turismo/r01Index/0000060481_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000060481_a1_rec_turismo/opendata/0000060481_a1_rec_turismo.zip"
  }, {
    "documentName" : "AC HOTEL GENERAL ALAVA",
    "turismDescription" : "Moderno hotel de tres estrellas situado en el centro de Vitoria-Gasteiz, junto al Palacio de Cong...",
    "turismDescription" : "Moderno hotel de tres estrellas situado en el centro de Vitoria-Gasteiz, junto al Palacio de Congresos Europa y a 8 minutos del aeropuerto. Dispone de 114 habitaciones con aire acondicionado, baño completo, caja fuerte, Internet, Wi-Fi, televisión por satélite y de pago, secador de pelo y teléfono. Además, cuenta con restaurante y seis modernos salones para organizar reuniones, entrevistas, conferencias o banquetes de entre 12 personas y 150 personas.",
    "templateType" : "Alojamientos",
    "locality" : "Vitoria-Gasteiz",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "945.215.000,0",
    "address" : "Avenida Gasteiz 79",
    "marks" : "Vitoria-Gasteiz",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "acgeneralalava@ac-hotels.com",
    "web" : "www.ac-hotels.com",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "3",
    "restaurant" : "1",
    "room" : "1",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HVI00093",
    "visit" : "",
    "capacity" : "191",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "1.009",
    "latitudelongitude" : "42.85083262,-2.68119245",
    "latwgs84" : "42.85083262",
    "lonwgs84" : "-2.68119245",
    "placename" : "",
    "address" : "",
    "municipality" : "Vitoria-Gasteiz",
    "municipalitycode" : "59",
    "postalcode" : "",
    "territory" : "Araba/Álava",
    "territorycode" : "1",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-ac-hotel-general-alava/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000112_a1_rec_turismo/es_112/112-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000112_a1_rec_turismo/es_112/data/112_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000112_a1_rec_turismo/r01Index/0000000112_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000112_a1_rec_turismo/opendata/0000000112_a1_rec_turismo.zip"
  }, {
    "documentName" : "ACHURI",
    "turismDescription" : "Céntrico hotel de una estrella ubicado en la capital alavesa. Dispone de 40 habitaciones, dobles ...",
    "turismDescription" : "Céntrico hotel de una estrella ubicado en la capital alavesa. Dispone de 40 habitaciones, dobles e individuales, equipadas con calefacción y televisión por cable. El hotel también cuenta con conexión gratuita WI-FI de Internet y teléfono. Asimismo, dispone de cafetería-bar, comedor y salón social.",
    "templateType" : "Alojamientos",
    "locality" : "Vitoria-Gasteiz",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "945.255.800,0",
    "address" : "Rioja  11",
    "marks" : "Vitoria-Gasteiz",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "hotelachurivitoria@gmail.com",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HVI00238",
    "visit" : "",
    "capacity" : "66",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "1.005",
    "latitudelongitude" : "42.84306683,-2.66822187",
    "latwgs84" : "42.84306683",
    "lonwgs84" : "-2.66822187",
    "placename" : "",
    "address" : "",
    "municipality" : "Vitoria-Gasteiz",
    "municipalitycode" : "59",
    "postalcode" : "",
    "territory" : "Araba/Álava",
    "territorycode" : "1",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-achuri/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000008_a1_rec_turismo/es_8/8-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000008_a1_rec_turismo/es_8/data/8_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000008_a1_rec_turismo/r01Index/0000000008_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000008_a1_rec_turismo/opendata/0000000008_a1_rec_turismo.zip"
  }, {
    "documentName" : "ACP MANAGEMENT, SOC COOP",
    "turismDescription" : "Apartamento situado en Zabalburu, una zona desde la que sus huéspedes podrán accede...",
    "turismDescription" : "<p>Apartamento situado en Zabalburu, una zona desde la que sus hu&eacute spedes podr&aacute n acceder f&aacute cilmente a pie o en transporte p&uacute blico a los lugares imprescindibles en una visita a Bilbao, desde callejear por el Casco Viejo, visitar museos como el Guggenheim o el Bellas Artes o salir de pintxos por la Gran V&iacute a o Indautxu.</p>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "",
    "address" : "Nicolás Alcorta, 1",
    "marks" : "Bilbao",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Apartamentos",
    "category" : "3",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "TBI00046",
    "visit" : "",
    "capacity" : "10",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.003",
    "latitudelongitude" : "43.2562281,-2.9337102",
    "latwgs84" : "43.2562281",
    "lonwgs84" : "-2.9337102",
    "placename" : "",
    "address" : "",
    "municipality" : "Bilbao",
    "municipalitycode" : "20",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/acp-management-soc-coop/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000208535_a1_rec_turismo/es_208535/208535-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000208535_a1_rec_turismo/es_208535/data/208535_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000208535_a1_rec_turismo/r01Index/0000208535_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000208535_a1_rec_turismo/opendata/0000208535_a1_rec_turismo.zip"
  }, {
    "documentName" : "AGARIMO",
    "turismDescription" : "Este alojamiento está ubicado en la zona industrial de la margen izquierda, a tan sólo 15 minutos...",
    "turismDescription" : "Este alojamiento está ubicado en la zona industrial de la margen izquierda, a tan sólo 15 minutos de Bilbao y muy bien comunicado mediante transporte público. <br/><br/>Cuenta con habitaciones individuales y dobles, todas ellas con baño propio, televisión y calefacción. <br/><br/>Además de alojamiento dispone de una cafetería-restaurante que ofrece menú del día. <br/>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "944.956.296,0",
    "address" : "Galindo Auzoa z.g.",
    "marks" : "Bilbao",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "agarimo@hotmail.com",
    "web" : "www.hostalrestauranteagarimo.es",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "1",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01254",
    "visit" : "",
    "capacity" : "72",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.510",
    "latitudelongitude" : "43.3033007918685,-3.0165406491821614",
    "latwgs84" : "43.3033007918685",
    "lonwgs84" : "-3.0165406491821614",
    "placename" : "",
    "address" : "",
    "municipality" : "Valle de Trápaga-Trapagaran",
    "municipalitycode" : "80",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/agarimo/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000079782_a1_rec_turismo/es_79782/79782-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000079782_a1_rec_turismo/es_79782/data/79782_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000079782_a1_rec_turismo/r01Index/0000079782_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000079782_a1_rec_turismo/opendata/0000079782_a1_rec_turismo.zip"
  }, {
    "documentName" : "AGINAGA",
    "turismDescription" : "Aginaga es un hotel de diseño moderno que ha apostado por la eficiencia energética sin dejar de l...",
    "turismDescription" : "Aginaga es un hotel de diseño moderno que ha apostado por la eficiencia energética sin dejar de lado la tradición. Todas sus habitaciones disponen de conexión Wi-Fi de Internet gratuita. Cuenta, además, con una sidrería y un restaurante dedicado a la cocina tradicional vasca.",
    "templateType" : "Alojamientos",
    "locality" : "Aginaga",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 370 668",
    "address" : "Aginaga Auzoa 31",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "info@aginagahotela.com",
    "web" : "http://www.aginagahotela.com/",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "2",
    "restaurant" : "1",
    "room" : "1",
    "productClub" : "1",
    "autocaravana" : "",
    "signatura" : "HSS00743",
    "visit" : "",
    "capacity" : "44",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.170",
    "latitudelongitude" : "43.2764269,-2.0725681000000122",
    "latwgs84" : "43.2764269",
    "lonwgs84" : "-2.0725681000000122",
    "placename" : "",
    "address" : "",
    "municipality" : "Usurbil",
    "municipalitycode" : "73",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamiento/hotel-aginaga/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000054401_a1_rec_turismo/es_54401/54401-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000054401_a1_rec_turismo/es_54401/data/54401_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000054401_a1_rec_turismo/r01Index/0000054401_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000054401_a1_rec_turismo/opendata/0000054401_a1_rec_turismo.zip"
  }, {
    "documentName" : "AIA",
    "turismDescription" : "Situado a 2 minutos a pie de la playa de la Zurriola y del Palacio de Congresos  Kursaal. El cent...",
    "turismDescription" : "Situado a 2 minutos a pie de la playa de la Zurriola y del Palacio de Congresos  Kursaal. El centro de la ciudad, con sus numerosas tiendas y el casco antiguo con sus bares de pintxos, restaurantes y vida nocturna están a sólo cinco minutos a pie. <br/><br/>Dispone de cocina de autoservicio que incluyen té, café, leche, cereales, galletas, etc. También hay una nevera, tostadora, hervidor de agua, un microondas y cafetera (pero sin cocina). Esta abierta abierta las 24 horas y no hay ningún costo extra por su uso. <br/><br/><br/>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 270 011",
    "address" : "Zabaleta  40",
    "marks" : "Costa Vasca,San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "albpaulo@hotmail.com",
    "web" : "pensionaia.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00713",
    "visit" : "",
    "capacity" : "9",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "1",
    "postalCode" : "20.002",
    "latitudelongitude" : "43.3254313,-1.9729132",
    "latwgs84" : "43.3254313",
    "lonwgs84" : "-1.9729132",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-aia/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000040801_a1_rec_turismo/es_40801/40801-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000040801_a1_rec_turismo/es_40801/data/40801_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000040801_a1_rec_turismo/r01Index/0000040801_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000040801_a1_rec_turismo/opendata/0000040801_a1_rec_turismo.zip"
  }, {
    "documentName" : "AIDA",
    "turismDescription" : "Pensión de 2 estrellas ubicada cerca de la estación de RENFE, de los Nuevos Juzgados, del Palacio...",
    "turismDescription" : "Pensión de 2 estrellas ubicada cerca de la estación de RENFE, de los Nuevos Juzgados, del Palacio de Congresos y Auditorio Kursaal así como de las playas de la Concha y la Zurriola. Dispone de 9 habitaciones provistas de internet, servicio de habitaciones, calefacción, aire acondicionado, televisión por cable y secador de pelo. También tiene salón social.",
    "templateType" : "Alojamientos",
    "locality" : "Donostia / San Sebastián",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 327 800",
    "address" : "Iztueta  9",
    "marks" : "Costa Vasca,San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "aida@pensionesconencanto.com",
    "web" : "http://www.pensionesconencanto.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00615",
    "visit" : "",
    "capacity" : "26",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.001",
    "latitudelongitude" : "43.32120999,-1.97528451",
    "latwgs84" : "43.32120999",
    "lonwgs84" : "-1.97528451",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-aida/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000009_a1_rec_turismo/es_9/9-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000009_a1_rec_turismo/es_9/data/9_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000009_a1_rec_turismo/r01Index/0000000009_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000009_a1_rec_turismo/opendata/0000000009_a1_rec_turismo.zip"
  }, {
    "documentName" : "AINTZIETA",
    "turismDescription" : "Alojamiento ubicado en una zona tranquila de la ciudad, en el barrio de Loiola muy cerca de la es...",
    "turismDescription" : "Alojamiento ubicado en una zona tranquila de la ciudad, en el barrio de Loiola muy cerca de la estación de tren.<br/><br/>Dispone de capacidad para 6 personas distribuidas en tres habitaciones dobles. <br/>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 457 540",
    "address" : "Aintzieta Ibilbidea 15",
    "marks" : "San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00604",
    "visit" : "",
    "capacity" : "6",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.014",
    "latitudelongitude" : "43.3050239,-1.9626130999999987",
    "latwgs84" : "43.3050239",
    "lonwgs84" : "-1.9626130999999987",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/aintzieta/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000078054_a1_rec_turismo/es_78054/78054-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078054_a1_rec_turismo/es_78054/data/78054_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078054_a1_rec_turismo/r01Index/0000078054_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078054_a1_rec_turismo/opendata/0000078054_a1_rec_turismo.zip"
  }, {
    "documentName" : "AITANA",
    "turismDescription" : "Moderno hotel situado al lado del recinto ferial FICOBA. Dispone de 19 habitaciones provistas de ...",
    "turismDescription" : "Moderno hotel situado al lado del recinto ferial FICOBA. Dispone de 19 habitaciones provistas de baño, internet, servicio de habitaciones, calefacción y televisión por cable. El hotel cuenta así mismo con cafetería-bar, restaurante, comedor, salón social y lavandería. Está rodeado de zonas verdes.",
    "templateType" : "Alojamientos",
    "locality" : "Irun",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 635 700",
    "address" : "Iparralde Etorbidea  51",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "1",
    "tourismEmail" : "hotelaitana@hotelaitana.com",
    "web" : "http://www.hotelaitana.com",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "1",
    "restaurant" : "1",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00630",
    "visit" : "",
    "capacity" : "32",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.304",
    "latitudelongitude" : "43.348564523084626,-1.7866730690002441",
    "latwgs84" : "43.348564523084626",
    "lonwgs84" : "-1.7866730690002441",
    "placename" : "",
    "address" : "",
    "municipality" : "Irun",
    "municipalitycode" : "45",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-aitana/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000010_a1_rec_turismo/es_10/10-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000010_a1_rec_turismo/es_10/data/10_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000010_a1_rec_turismo/r01Index/0000000010_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000010_a1_rec_turismo/opendata/0000000010_a1_rec_turismo.zip"
  }, {
    "documentName" : "AKELARRE",
    "turismDescription" : "Pensión de dos estrellas ubicada en el municipio de Gernika-Lumo. Dispone de 17 habit...",
    "turismDescription" : "<p>Pensi&oacute n de dos estrellas ubicada en el municipio de <strong>Gernika-Lumo</strong>.</p><p>&nbsp </p><p>Dispone de 17 habitaciones dobles e individuales, todas ellas provistas de ba&ntilde o, televisi&oacute n, calefacci&oacute n, tel&eacute fono e internet. Tambi&eacute n tiene sal&oacute n social y lavander&iacute a. <br/>La pensi&oacute n est&aacute  en una zona peatonal, el acceso m&aacute s cercano con el coche est&aacute  a 30 metros.</p><p>&nbsp </p><p>La estaci&oacute n de autob&uacute s y de tren del centro de Gernika se encuentran a 70 metros. <br/></p>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "946.270.197,0",
    "address" : "Barrenkalea  5",
    "marks" : "Costa Vasca,Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "akelarre@hotelakelarre.com",
    "web" : "http://www.hotelakelarre.com/",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01131",
    "visit" : "",
    "capacity" : "32",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.300",
    "latitudelongitude" : "43.31510093,-2.67760429",
    "latwgs84" : "43.31510093",
    "lonwgs84" : "-2.67760429",
    "placename" : "",
    "address" : "",
    "municipality" : "Gernika-Lumo",
    "municipalitycode" : "46",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-akelarre/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000011_a1_rec_turismo/es_11/11-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000011_a1_rec_turismo/es_11/data/11_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000011_a1_rec_turismo/r01Index/0000000011_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000011_a1_rec_turismo/opendata/0000000011_a1_rec_turismo.zip"
  }, {
    "documentName" : "AKELARRE",
    "turismDescription" : "Es un hotel de lujo donde el chef Pedro Subijana eleva la experiencia de su icónico restau...",
    "turismDescription" : "<p>Es un hotel de lujo donde el chef <strong>Pedro Subijana</strong> eleva la experiencia de su ic&oacute nico restaurante de tres estrellas Michelin. Est&aacute  situado en un magn&iacute fico lugar entre la monta&ntilde a y el mar a escasos kil&oacute metros de la capital guipuzcoana, con unas vistas panor&aacute micas al <strong>Golfo de Bizkaia.&nbsp </strong><br /><br/>El hotel dispone de espaciosas habitaciones de entre 50 y 100 metros, todas decoradas con un estilo sobrio y elegante, en el que destacan los materiales nobles, la gran calidad de los acabados y el equipamiento. Cada una de las habitaciones dispone adem&aacute s de su propia y amplia terraza amueblada donde relajarse.&nbsp <br /><br/>La suite Akelarre, de 100m2, dispone de vestidor, una amplia terraza con enormes ventanales y una peque&ntilde a piscina exterior.<br /><br/>Este lujoso alojamiento de espacios elegantes y contempor&aacute neos tiene una zona de Spa&amp Wellness y una bodega que, con su ic&oacute nico restaurante convierten a <strong>Akelarre </strong>en una experiencia &uacute nica con las mejores vistas sobre la costa vasca.</p>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943.311.208,0",
    "address" : "Padre Orcolaga, 56 (Igeldo)",
    "marks" : "San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "info@akelarre.net",
    "web" : "https://www.akelarre.net/es/hotel",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "5",
    "restaurant" : "1",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00833",
    "visit" : "",
    "capacity" : "44",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.008",
    "latitudelongitude" : "43.30740246487573,-2.0440846000000192",
    "latwgs84" : "43.30740246487573",
    "lonwgs84" : "-2.0440846000000192",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/akelarre/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000200434_a1_rec_turismo/es_200434/200434-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000200434_a1_rec_turismo/es_200434/data/200434_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000200434_a1_rec_turismo/r01Index/0000200434_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000200434_a1_rec_turismo/opendata/0000200434_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALAMEDA",
    "turismDescription" : "Pensión de dos estrellas ubicada en el centro de la capital guipuzcoana que dispone de habitacion...",
    "turismDescription" : "Pensión de dos estrellas ubicada en el centro de la capital guipuzcoana que dispone de habitaciones provistas de calefacción, televisión por cable, mini-bar, secador de pelo e internet. También cuenta con un salón social.",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943.426.449,0",
    "address" : "Boulevard  16",
    "marks" : "San Sebastián,Costa Vasca",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "reservas@pensionalameda.com",
    "web" : "www.pensionalameda.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "1",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00666",
    "visit" : "",
    "capacity" : "20",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.003",
    "latitudelongitude" : "43.32230540135321,-1.984255313873291",
    "latwgs84" : "43.32230540135321",
    "lonwgs84" : "-1.984255313873291",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-alameda/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000013_a1_rec_turismo/es_13/13-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000013_a1_rec_turismo/es_13/data/13_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000013_a1_rec_turismo/r01Index/0000000013_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000013_a1_rec_turismo/opendata/0000000013_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALAMEDA",
    "turismDescription" : "Hotel ubicado en una hermosa villa, a pocos metros de la playa de Zarautz. Dispone de 40 habitaci...",
    "turismDescription" : "Hotel ubicado en una hermosa villa, a pocos metros de la playa de Zarautz. Dispone de 40 habitaciones dobles e individuales, todas ellas provistas de baño completo, calefacción, aire acondicionado, internet, televisión por cable, mini-bar y secador de pelo. El hotel cuenta así mismo con cafetería, restaurante, garaje, salón social y para convenciones, jardín-terraza y solarium.",
    "templateType" : "Alojamientos",
    "locality" : "Zarautz",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 132 737",
    "address" : "Seitximeneta  4",
    "marks" : "Costa Vasca",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "administracion@hotelalameda.net",
    "web" : "http://www.hotelalameda.net",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "2",
    "restaurant" : "1",
    "room" : "1",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00564",
    "visit" : "",
    "capacity" : "73",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "1",
    "postalCode" : "20.800",
    "latitudelongitude" : "43.28553885,-2.17017163",
    "latwgs84" : "43.28553885",
    "lonwgs84" : "-2.17017163",
    "placename" : "",
    "address" : "",
    "municipality" : "Zarautz",
    "municipalitycode" : "79",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-alameda/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000014_a1_rec_turismo/es_14/14-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000014_a1_rec_turismo/es_14/data/14_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000014_a1_rec_turismo/r01Index/0000000014_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000014_a1_rec_turismo/opendata/0000000014_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALBINO",
    "turismDescription" : "La pensión Albino se encuentra en el barrio de Santutxu a cinco minutos andando de la Basílica de...",
    "turismDescription" : "La pensión Albino se encuentra en el barrio de Santutxu a cinco minutos andando de la Basílica de Begoña, patrona de Bizkaia que domina Bilbao desde un alto. <br/><br/>Dispone tanto de habitaciones individuales como de dobles.",
    "templateType" : "Alojamientos",
    "locality" : "Bilbao",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "",
    "address" : "Pablo Zamarripa  10",
    "marks" : "Bilbao",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI00771",
    "visit" : "",
    "capacity" : "9",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.006",
    "latitudelongitude" : "",
    "latwgs84" : "",
    "lonwgs84" : "",
    "placename" : "",
    "address" : "",
    "municipality" : "Bilbao Bilbao",
    "municipalitycode" : "020 020",
    "postalcode" : "",
    "territory" : "Bizkaia Bizkaia",
    "territorycode" : "48 48",
    "country" : "España España",
    "countrycode" : "108 108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/albino/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000078301_a1_rec_turismo/es_78301/78301-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078301_a1_rec_turismo/es_78301/data/78301_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078301_a1_rec_turismo/r01Index/0000078301_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078301_a1_rec_turismo/opendata/0000078301_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALBIZABAL",
    "turismDescription" : "Este alojamiento está situado en el centro de Amurrio, junto a la zona de tiendas y restauración....",
    "turismDescription" : "Este alojamiento está situado en el centro de Amurrio, junto a la zona de tiendas y restauración. <br/><br/>Todas las habitaciones disponen de baño completo, TV y Wi-Fi. <br/><br/>Se encuentra a medio camino entre Bilbao (30 km) y Vitoria-Gasteiz (40 km) y muy cerca del Parque Natural de Gorbeia.<br/>",
    "templateType" : "Alojamientos",
    "locality" : "Amurrio",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "945 066 124",
    "address" : "Aiara  10",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "http://www.facebook.com/people/Amurrio-Albizabal/100008862150240",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HVI00405",
    "visit" : "",
    "capacity" : "5",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "1.470",
    "latitudelongitude" : "43.0519948,-3.003497799999991",
    "latwgs84" : "43.0519948",
    "lonwgs84" : "-3.003497799999991",
    "placename" : "",
    "address" : "",
    "municipality" : "Amurrio",
    "municipalitycode" : "2",
    "postalcode" : "",
    "territory" : "Araba/Álava",
    "territorycode" : "1",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/albizabal/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000080841_a1_rec_turismo/es_80841/80841-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000080841_a1_rec_turismo/es_80841/data/80841_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000080841_a1_rec_turismo/r01Index/0000080841_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000080841_a1_rec_turismo/opendata/0000080841_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALCAZAR",
    "turismDescription" : "Hotel ubicado en el municipio fronterizo de Irun, en el centro de la localidad, rodeado de jardin...",
    "turismDescription" : "<p>Hotel ubicado en el municipio fronterizo de <strong>Irun</strong>, en el centro de la localidad, rodeado de jardines y de un &aacute rea de arbolado de 3.500 metros cuadrados. Dispone de 48 habitaciones dobles e individuales con vistas al exterior, ba&ntilde o completo, televisi&oacute n, tel&eacute fono y secador de pelo. Adem&aacute s, el hotel dispone de WiFi sin coste adicional tanto en habitaciones como en zonas comunes y cuenta con dos salas de reuniones, parking gratuito y restaurante con terraza.</p><p>&nbsp </p><p>Se encuentra a 300 metros del recinto ferial <strong>FICOBA</strong>.</p>",
    "templateType" : "Alojamientos",
    "locality" : "Irun",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 620 900",
    "address" : "Iparralde  Etorbidea 11",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "1",
    "tourismEmail" : "info@hotelalcazar.net",
    "web" : "http://www.hotelalcazar.net",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "3",
    "restaurant" : "1",
    "room" : "1",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00027",
    "visit" : "",
    "capacity" : "87",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.302",
    "latitudelongitude" : "43.34138075,-1.79046264",
    "latwgs84" : "43.34138075",
    "lonwgs84" : "-1.79046264",
    "placename" : "",
    "address" : "",
    "municipality" : "Irun",
    "municipalitycode" : "45",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-alcazar/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000015_a1_rec_turismo/es_15/15-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000015_a1_rec_turismo/es_15/data/15_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000015_a1_rec_turismo/r01Index/0000000015_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000015_a1_rec_turismo/opendata/0000000015_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALDAMA",
    "turismDescription" : "Situado en una finca ajardinada en el centro de Amurrio, el Hotel Restaurante Aldama es un singul...",
    "turismDescription" : "<p>Situado en una finca ajardinada en el centro de <strong>Amurrio</strong>, el Hotel Restaurante Aldama es un singular edificio que ofrece 8 acogedoras habitaciones.</p><p>&nbsp </p><p>Todas est&aacute n dotadas de calefacci&oacute n, ba&ntilde o, televisi&oacute n, tel&eacute fono y acceso a Internet gratuito. Adem&aacute s, disponen de dos acogedores comedores, con una capacidad para 36 comensales, donde poder disfrutar de una comida de empresa, cualquier celebraci&oacute n o simplemente una reuni&oacute n de amigos.</p>",
    "templateType" : "Alojamientos",
    "locality" : "Amurrio",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "945.066.646,0",
    "address" : "Dionisio Aldama  12",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "hotel@hotelrestaurantealdama.com",
    "web" : "https://hotelrestaurantealdama.com/es/",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "1",
    "restaurant" : "1",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HVI00393",
    "visit" : "",
    "capacity" : "15",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "1.470",
    "latitudelongitude" : "43.0501069,-3.001129",
    "latwgs84" : "43.0501069",
    "lonwgs84" : "-3.001129",
    "placename" : "",
    "address" : "",
    "municipality" : "Amurrio",
    "municipalitycode" : "2",
    "postalcode" : "",
    "territory" : "Araba/Álava",
    "territorycode" : "1",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-aldama/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000031001_a1_rec_turismo/es_31001/31001-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000031001_a1_rec_turismo/es_31001/data/31001_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000031001_a1_rec_turismo/r01Index/0000031001_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000031001_a1_rec_turismo/opendata/0000031001_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALDAMAR",
    "turismDescription" : "Pensión de 2 estrellas ubicada en la capital guipuzcoana que dispone de 10 habitaciones dobles pr...",
    "turismDescription" : "Pensión de 2 estrellas ubicada en la capital guipuzcoana que dispone de 10 habitaciones dobles provistas de baño completo, televisión, teléfono directo, caja fuerte y mini-bar. También disponen de internet Wi-Fi.",
    "templateType" : "Alojamientos",
    "locality" : "Donostia / San Sebastián",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 430 143",
    "address" : "Aldamar  2",
    "marks" : "San Sebastián,Costa Vasca",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "pension@pensionaldamar.com",
    "web" : "http://www.pensionaldamar.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00632",
    "visit" : "",
    "capacity" : "20",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.004",
    "latitudelongitude" : "43.32316976,-1.98205933",
    "latwgs84" : "43.32316976",
    "lonwgs84" : "-1.98205933",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-aldamar/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000016_a1_rec_turismo/es_16/16-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000016_a1_rec_turismo/es_16/data/16_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000016_a1_rec_turismo/r01Index/0000000016_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000016_a1_rec_turismo/opendata/0000000016_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALDATZETA",
    "turismDescription" : "El alojamiento se encuentra en el casco antiguo de Bermeo, a 3 y 12 kilómetros, respectivamente, ...",
    "turismDescription" : "El alojamiento se encuentra en el casco antiguo de Bermeo, a 3 y 12 kilómetros, respectivamente, de Mundaka y Bakio, localidades conocidas por sus olas y tradición surfera. Todas las habitaciones son exteriores y cuentan con los siguientes servicios: calefacción, baño completo y televisión.",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "946.187.703,0",
    "address" : "Erremedio  24",
    "marks" : "Costa Vasca",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "reservas@aldatzeta.com",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01202",
    "visit" : "",
    "capacity" : "10",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.370",
    "latitudelongitude" : "43.4198209,-2.723961",
    "latwgs84" : "43.4198209",
    "lonwgs84" : "-2.723961",
    "placename" : "",
    "address" : "",
    "municipality" : "Bermeo",
    "municipalitycode" : "17",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamiento/pension-aldatzeta/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000043181_a1_rec_turismo/es_43181/43181-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000043181_a1_rec_turismo/es_43181/data/43181_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000043181_a1_rec_turismo/r01Index/0000043181_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000043181_a1_rec_turismo/opendata/0000043181_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALEMANA",
    "turismDescription" : "Pensión de 2 estrellas ubicada en la capital guipuzcoana que dispone de 20 habitaciones dobles pr...",
    "turismDescription" : "Pensión de 2 estrellas ubicada en la capital guipuzcoana que dispone de 20 habitaciones dobles provistas de baño completo, televisión, teléfono directo, caja fuerte y mini-bar. También disponen de conexión Wi-Fi.",
    "templateType" : "Alojamientos",
    "locality" : "Donostia / San Sebastián",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 462 544",
    "address" : "San Martín 53",
    "marks" : "Costa Vasca,San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "1",
    "tourismEmail" : "reservas@hostalalemana.com",
    "web" : "http://www.hostalalemana.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00055",
    "visit" : "",
    "capacity" : "41",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.007",
    "latitudelongitude" : "43.31557361,-1.98675443",
    "latwgs84" : "43.31557361",
    "lonwgs84" : "-1.98675443",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-alemana/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000017_a1_rec_turismo/es_17/17-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000017_a1_rec_turismo/es_17/data/17_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000017_a1_rec_turismo/r01Index/0000000017_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000017_a1_rec_turismo/opendata/0000000017_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALICIA ZZZ B&B",
    "turismDescription" : "AliciaZzz Bed and Breakfast Bilbao (B and B Bilbao) está ambientado en las aventuras de Alicia en...",
    "turismDescription" : "AliciaZzz Bed and Breakfast Bilbao (B and B Bilbao) está ambientado en las aventuras de Alicia en el País de las Maravillas. El alojamiento consta de seis habitaciones amplias, luminosas y con baño individual, desde las cuales se puede observar la vida cotidiana de los bilbaínos. Además, disponen de televisión e Internet.",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "946.792.198,0",
    "address" : "Sombrerería  1",
    "marks" : "Bilbao",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "1",
    "tourismEmail" : "info@aliciazzz.com",
    "web" : "www.aliciazzz.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01230",
    "visit" : "",
    "capacity" : "11",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.005",
    "latitudelongitude" : "43.258549601014906,-2.9233288764953613",
    "latwgs84" : "43.258549601014906",
    "lonwgs84" : "-2.9233288764953613",
    "placename" : "",
    "address" : "",
    "municipality" : "Bilbao",
    "municipalitycode" : "20",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-alicia-zzz-b-b/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000041761_a1_rec_turismo/es_41761/41761-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000041761_a1_rec_turismo/es_41761/data/41761_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000041761_a1_rec_turismo/r01Index/0000041761_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000041761_a1_rec_turismo/opendata/0000041761_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALMA DE ROMERO",
    "turismDescription" : "Hotel ubicado en plena naturaleza, en el Valle de Carranza y rodeado de un jardín de 10.000 m². D...",
    "turismDescription" : "Hotel ubicado en plena naturaleza, en el Valle de Carranza y rodeado de un jardín de 10.000 m². Dispone de 7 habitaciones dobles y una individual, todas dotadas de bañera de hidromasaje, conexión wifi gratuita, teléfono, televisión, DVD, mini-bar, secador de pelo, espejo de aumento y productos cosméticos naturales. Además, algunas cuentan con terraza y sala. El hotel tiene también sala de estar con ordenador y comedor en el que ofrece desayunos y cenas. Venta de productos de regalo.",
    "templateType" : "Alojamientos",
    "locality" : "Ahedo",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "946 806 869",
    "address" : "Ahedo Auzoa 25",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "lourdes@almaderomero.com",
    "web" : "http://www.almaderomero.com",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01197",
    "visit" : "",
    "capacity" : "15",
    "store" : "1",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.891",
    "latitudelongitude" : "43.22986356,-3.35585788",
    "latwgs84" : "43.22986356",
    "lonwgs84" : "-3.35585788",
    "placename" : "",
    "address" : "",
    "municipality" : "Karrantza Harana/Valle de Carranza",
    "municipalitycode" : "22",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-alma-de-romero/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000014123_a1_rec_turismo/es_14123/14123-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000014123_a1_rec_turismo/es_14123/data/14123_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000014123_a1_rec_turismo/r01Index/0000014123_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000014123_a1_rec_turismo/opendata/0000014123_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALTAIR",
    "turismDescription" : "Pensión de 2 estrellas ubicada en la capital guipuzcoana que dispone de 7 habitaciones dobles y u...",
    "turismDescription" : "Pensión de 2 estrellas ubicada en la capital guipuzcoana que dispone de 7 habitaciones dobles y una individual provistas de cuarto de baño, televisión plana y caja fuerte con capacidad para guardar un ordenador portátil normal. También disponen de Internet Wi-Fi y un ordenador en la zona común con acceso a Internet gratuito para los clientes.",
    "templateType" : "Alojamientos",
    "locality" : "Donostia / San Sebastián",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 293 133",
    "address" : "Padre Larroca 3",
    "marks" : "Costa Vasca,San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "1",
    "tourismEmail" : "pensionaltair@pension-altair.com",
    "web" : "http://www.pension-altair.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "2",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00700",
    "visit" : "",
    "capacity" : "15",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.001",
    "latitudelongitude" : "43.322543,-1.973791",
    "latwgs84" : "43.322543",
    "lonwgs84" : "-1.973791",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-altair/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000026942_a1_rec_turismo/es_26942/26942-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000026942_a1_rec_turismo/es_26942/data/26942_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000026942_a1_rec_turismo/r01Index/0000026942_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000026942_a1_rec_turismo/opendata/0000026942_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALTAMIRA 15",
    "turismDescription" : "Situado en el barrio bilbaíno de Altamira, el visitante podrá encontrar en este apartamento todas...",
    "turismDescription" : "Situado en el barrio bilbaíno de Altamira, el visitante podrá encontrar en este apartamento todas las comodidades necesarias para una estancia agradable en la capital y sus alrededores.<br/><br/>El alojamiento cuenta con un dormitorio que contiene una cama de matrimonio grande y dos sofás cama, y un salón con otros dos sofás cama. Es un lugar ideal para acudir a la ciudad con amigos o familia, de una forma práctica y económica.<br/><br/>Altamira 15 está emplazado en un lugar tranquilo, en el cual el visitante podrá apreciar el día a día de la capital vizcaína y además descubrir una vista panorámica de Bilbao con emblemáticos edificios tales como el Estadio San Mamés, la Grúa de la Carola, la Torre Iberdrola o el Museo Guggenheim.",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "",
    "address" : "Barrio Altamira Nº 15",
    "marks" : "Bilbao",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "atalltamira15@gmail.com",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Apartamentos",
    "category" : "3",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "TBI00027",
    "visit" : "",
    "capacity" : "14",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.002",
    "latitudelongitude" : "43.2623012,-2.9630792000000383",
    "latwgs84" : "43.2623012",
    "lonwgs84" : "-2.9630792000000383",
    "placename" : "",
    "address" : "",
    "municipality" : "Bilbao",
    "municipalitycode" : "20",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamiento/altamira15/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000092785_a1_rec_turismo/es_92785/92785-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000092785_a1_rec_turismo/es_92785/data/92785_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000092785_a1_rec_turismo/r01Index/0000092785_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000092785_a1_rec_turismo/opendata/0000092785_a1_rec_turismo.zip"
  }, {
    "documentName" : "ALTXERRI",
    "turismDescription" : "Alojamiento ubicado en el municipio de  Aia, se encuentra cerca del Parque Natural de Pagoeta que...",
    "turismDescription" : "Alojamiento ubicado en el municipio de  Aia, se encuentra cerca del Parque Natural de Pagoeta que ofrece recorridos señalizados para pasear o visitas guiada a la Ferreria de Agorregi?etc",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943.830.762,0",
    "address" : "Olaskoegia Auzoa 32",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00755",
    "visit" : "",
    "capacity" : "9",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.809",
    "latitudelongitude" : "43.26857813858993,-2.133306144982953",
    "latwgs84" : "43.26857813858993",
    "lonwgs84" : "-2.133306144982953",
    "placename" : "",
    "address" : "",
    "municipality" : "Aia",
    "municipalitycode" : "16",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/altxerri/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000078261_a1_rec_turismo/es_78261/78261-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078261_a1_rec_turismo/es_78261/data/78261_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078261_a1_rec_turismo/r01Index/0000078261_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078261_a1_rec_turismo/opendata/0000078261_a1_rec_turismo.zip"
  }, {
    "documentName" : "AMAIA",
    "turismDescription" : "El establecimiento ocupa una casa con jardín situada a pocos metros del casco histórico de Orduña...",
    "turismDescription" : "El establecimiento ocupa una casa con jardín situada a pocos metros del casco histórico de Orduña, declarado Conjunto Histórico-Monumental.   En las inmediaciones se puede visitar el impresionante cañón donde nace el río Nervión.<br/><br/>La pensión dispone de aparcamiento propio.<br/>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "945 383 090",
    "address" : "San Francisco Auzoa 22",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HBI01120",
    "visit" : "",
    "capacity" : "19",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.460",
    "latitudelongitude" : "42.9920929,-3.0099155000000337",
    "latwgs84" : "42.9920929",
    "lonwgs84" : "-3.0099155000000337",
    "placename" : "",
    "address" : "",
    "municipality" : "Urduña/Orduña",
    "municipalitycode" : "74",
    "postalcode" : "",
    "territory" : "Bizkaia",
    "territorycode" : "48",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-amaia/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000078332_a1_rec_turismo/es_78332/78332-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078332_a1_rec_turismo/es_78332/data/78332_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078332_a1_rec_turismo/r01Index/0000078332_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078332_a1_rec_turismo/opendata/0000078332_a1_rec_turismo.zip"
  }, {
    "documentName" : "AMAIUR",
    "turismDescription" : "La pensión Amaiur se encuentra en el corazón de la parte vieja donostiarra.  &nbs...",
    "turismDescription" : "<p>La pensi&oacute n Amaiur se encuentra en el coraz&oacute n de la <strong>parte vieja donostiarra</strong>. <br/> <br/></p><p>&nbsp </p><p>Su ubicaci&oacute n permite tener al alcance los lugares m&aacute s emblem&aacute ticos de <strong>San Sebasti&aacute n</strong>: el puerto, las <strong>playas </strong>y especialmente la <strong>zona de bares de pintxos y restaurantes</strong> m&aacute s famosa de la ciudad. <br/> <br/>Entre sus habitaciones, algunas tienen balc&oacute n y ba&ntilde o privado y todas disponen de televisor de pantalla plana v&iacute a sat&eacute lite y calefacci&oacute n. <br/></p><p>&nbsp </p><p>Abre 24 horas y dispone de WiFi gratis en las habitaciones y en los espacios comunes.</p>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943.429.654,0",
    "address" : "31 de Agosto Kalea 44",
    "marks" : "San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "info@pensionamaiur.com",
    "web" : "http://www.pensionamaiur.com",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00541",
    "visit" : "",
    "capacity" : "9",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.003",
    "latitudelongitude" : "43.32400465330286,-1.9861453772807636",
    "latwgs84" : "43.32400465330286",
    "lonwgs84" : "-1.9861453772807636",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/amaiur/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000078037_a1_rec_turismo/es_78037/78037-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078037_a1_rec_turismo/es_78037/data/78037_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078037_a1_rec_turismo/r01Index/0000078037_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078037_a1_rec_turismo/opendata/0000078037_a1_rec_turismo.zip"
  }, {
    "documentName" : "AMALUR",
    "turismDescription" : "Situada en el centro de la ciudad, junto a la playa de La Concha, permite al viajero, disfrutar d...",
    "turismDescription" : "Situada en el centro de la ciudad, junto a la playa de La Concha, permite al viajero, disfrutar de la Parte Vieja y acceder a pie a los principales lugares turísticos, como el puerto o el Palacio de Congresos Kursaal.<br/><br/>El check in es de las 9:00 a 23.00<br/>",
    "templateType" : "Alojamientos",
    "locality" : "Donostia / San Sebastián",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "",
    "address" : "San Martín 43",
    "marks" : "San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00538",
    "visit" : "",
    "capacity" : "10",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.007",
    "latitudelongitude" : "",
    "latwgs84" : "",
    "lonwgs84" : "",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián Donostia / San Sebastián",
    "municipalitycode" : "069 069",
    "postalcode" : "",
    "territory" : "Gipuzkoa Gipuzkoa",
    "territorycode" : "20 20",
    "country" : "España España",
    "countrycode" : "108 108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/amalur/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000078035_a1_rec_turismo/es_78035/78035-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078035_a1_rec_turismo/es_78035/data/78035_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078035_a1_rec_turismo/r01Index/0000078035_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078035_a1_rec_turismo/opendata/0000078035_a1_rec_turismo.zip"
  }, {
    "documentName" : "AMALURRA",
    "turismDescription" : "Hotel y albergue situado en Artzentales, en una zona rural muy tranquila y rodeada de verde. El h...",
    "turismDescription" : "<p>Hotel y albergue situado en Artzentales, en una zona rural muy tranquila y rodeada de verde. El hotel dispone de 17 habitaciones con ba&ntilde o, calefacci&oacute n y tel&eacute fono. El albergue puede acoger 60 personas en habitaciones de 6 plazas con calefacci&oacute n y ba&ntilde os compartidos. Est&aacute  especialmente preparado para acoger congresos, cursos, seminarios y similares en un ambiente de serenidad y paz. El conjunto est&aacute  rodeado de jardines y cuenta con terrazas, carpa movil, restaurante de comida casera y/o vegetariana para 100 personas, sauna natural en una caba&ntilde a, salas multifuncionales, sala de meditaci&oacute n y parque infantil.</p>",
    "templateType" : "Alojamientos",
    "locality" : "Traslaviña",
    "qualityQ" : "1",
    "qualityIconDescription" : "Q de calidad",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "946.109.540,0",
    "address" : "La Reneja Auzoa 35",
    "marks" : "Montes y Valles vascos",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "amalurra@arrakis.es",
    "web" : "https://amalurra.com/",
    "importance" : "",
    "lodgingType" : "Hoteles",
    "category" : "1",
    "restaurant" : "1",
    "room" : "1",
    "productClub" : "1",
    "autocaravana" : "",
    "signatura" : "HBI01146",
    "visit" : "",
    "capacity" : "32",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "48.879",
    "latitudelongitude" : "",
    "latwgs84" : "",
    "lonwgs84" : "",
    "placename" : "",
    "address" : "",
    "municipality" : "Artzentales Artzentales",
    "municipalitycode" : "008 008",
    "postalcode" : "",
    "territory" : "Bizkaia Bizkaia",
    "territorycode" : "48 48",
    "country" : "España España",
    "countrycode" : "108 108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/hotel-amalurra/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000000022_a1_rec_turismo/es_22/22-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000022_a1_rec_turismo/es_22/data/22_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000022_a1_rec_turismo/r01Index/0000000022_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000000022_a1_rec_turismo/opendata/0000000022_a1_rec_turismo.zip"
  }, {
    "documentName" : "AMARA",
    "turismDescription" : "Situada en el barrio de Amara, cerca del estadio de fútbol de Anoeta, y muy bien comunicad...",
    "turismDescription" : "<p>Situada en el barrio de Amara, cerca del estadio de f&uacute tbol de Anoeta, y muy bien comunicada con el centro urbano y el casco viejo de la ciudad. <br/> <br/>Dispone de habitaciones con cama de matrimonio o individuales con la posibilidad de camas supletorias. <br/></p>",
    "templateType" : "Alojamientos",
    "locality" : "",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "943 468 472",
    "address" : "Isabel II Etorbidea 2",
    "marks" : "San Sebastián",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "pensionamara@hotmail.es",
    "web" : "",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HSS00586",
    "visit" : "",
    "capacity" : "12",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "20.011",
    "latitudelongitude" : "43.3051518,-1.975282600000014",
    "latwgs84" : "43.3051518",
    "lonwgs84" : "-1.975282600000014",
    "placename" : "",
    "address" : "",
    "municipality" : "Donostia / San Sebastián",
    "municipalitycode" : "69",
    "postalcode" : "",
    "territory" : "Gipuzkoa",
    "territorycode" : "20",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/amara/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000078047_a1_rec_turismo/es_78047/78047-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078047_a1_rec_turismo/es_78047/data/78047_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078047_a1_rec_turismo/r01Index/0000078047_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000078047_a1_rec_turismo/opendata/0000078047_a1_rec_turismo.zip"
  }, {
    "documentName" : "AMAYA",
    "turismDescription" : "Situada en pleno corazón de Vitoria-Gasteiz, muy cerca de la Plaza de la Virgen Blanca, el...",
    "turismDescription" : "<p>Situada en pleno coraz&oacute n de <strong>Vitoria-Gasteiz</strong>, muy cerca de la<strong> Plaza de la Virgen Blanca</strong>, el alojamiento est&aacute  situado en un edificio recientemente reformado desde el que el acceso a los principales lugares de visita tur&iacute stica se hace perfectamente a pie, incluyendo las zonas comerciales y las de ocio nocturno, as&iacute  como las principales zonas gastron&oacute micas de la ciudad. <br/> <br/></p><p>&nbsp </p><p>A pocos metros hay una parada de autob&uacute s y varios parkings p&uacute blicos. Las habitaciones cuentan con ba&ntilde o completo, televisi&oacute n y Wifi.</p>",
    "templateType" : "Alojamientos",
    "locality" : "Vitoria-Gasteiz",
    "qualityQ" : "",
    "qualityIconDescription" : "",
    "accesibility" : "",
    "accesibilityIconDescription" : "",
    "phone" : "945.255.497,0",
    "address" : "La Paz  15",
    "marks" : "Vitoria-Gasteiz",
    "physical" : "0",
    "visual" : "0",
    "auditive" : "0",
    "intellectual" : "0",
    "organic" : "0",
    "qualityAssurance" : "",
    "tourismEmail" : "",
    "web" : "http://www.pensionamaia.com/",
    "importance" : "",
    "lodgingType" : "Pensiones",
    "category" : "1",
    "restaurant" : "",
    "room" : "",
    "productClub" : "",
    "autocaravana" : "",
    "signatura" : "HVI00348",
    "visit" : "",
    "capacity" : "19",
    "store" : "",
    "gastronomical" : "",
    "surfing" : "",
    "postalCode" : "1.004",
    "latitudelongitude" : "42.8458411,-2.668175099999985",
    "latwgs84" : "42.8458411",
    "lonwgs84" : "-2.668175099999985",
    "placename" : "",
    "address" : "",
    "municipality" : "Vitoria-Gasteiz",
    "municipalitycode" : "59",
    "postalcode" : "",
    "territory" : "Araba/Álava",
    "territorycode" : "1",
    "country" : "España",
    "countrycode" : "108",
    "phone" : "",
    "email" : "",
    "webpage" : "",
    "friendlyUrl" : "https://turismoa.euskadi.eus/es/alojamientos/pension-amaya/aa30-12375/es/",
    "physicalUrl" : "https://turismoa.euskadi.eus/aa30-12375/es/contenidos/a_alojamiento/0000077623_a1_rec_turismo/es_77623/77623-ficha2.html",
    "dataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000077623_a1_rec_turismo/es_77623/data/77623_openData.xml",
    "metadataXML" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000077623_a1_rec_turismo/r01Index/0000077623_a1_rec_turismo-idxContent.xml",
    "zipFile" : "https://turismoa.euskadi.eus/contenidos/a_alojamiento/0000077623_a1_rec_turismo/opendata/0000077623_a1_rec_turismo.zip"
  }
  
  
];

db = connect("localhost:27017/admin");
db.auth('almi', 'Almi123');
db = db.getSiblingDB('Bilbao');

db.hoteles.insert(hoteles);
